//! Detail pages for YouTube Music collections: playlists, albums, artists.

use std::collections::HashMap;

use rustypipe::client::RustyPipe;
use rustypipe::model::MusicArtist;
use tauri::{AppHandle, Runtime};

use super::dto::{to_album_detail, to_artist_detail, to_playlist_detail};
use super::{
    validate_browse_id, yt_client, YtAlbumDetail, YtArtistDetail, YtError, YtPlaylistDetail,
};

/// Works for `PL…`, `OLAK5uy_…` and `RDCLAK…` playlist ids.
#[tauri::command]
pub async fn yt_music_playlist<R: Runtime>(
    app: AppHandle<R>,
    id: String,
) -> Result<YtPlaylistDetail, YtError> {
    let id = validate_browse_id(id)?;
    let rp = yt_client(&app).await?;
    let playlist = rp.query().music_playlist(&id).await?;
    Ok(to_playlist_detail(playlist))
}

/// `MPREb_…` album browse ids only.
#[tauri::command]
pub async fn yt_music_album<R: Runtime>(
    app: AppHandle<R>,
    id: String,
) -> Result<YtAlbumDetail, YtError> {
    let id = validate_browse_id(id)?;
    let rp = yt_client(&app).await?;
    let album = rp.query().music_album(&id).await?;
    Ok(to_album_detail(album))
}

/// `UC…` channel ids. Top tracks + albums + featured playlists in one call;
/// `all_albums=false` skips the extra per-"More"-button requests.
#[tauri::command]
pub async fn yt_music_artist<R: Runtime>(
    app: AppHandle<R>,
    id: String,
) -> Result<YtArtistDetail, YtError> {
    let id = validate_browse_id(id)?;
    let rp = yt_client(&app).await?;
    let mut artist = rp.query().music_artist(&id, false).await?;
    fill_top_track_durations(&rp, &mut artist).await;
    Ok(to_artist_detail(artist))
}

/// Artist pages never carry track durations (`TrackItem::duration` is `None`
/// there), but the artist's autogenerated tracks playlist does — fetch its
/// first page and merge durations by video id. Best-effort: any failure just
/// leaves durations empty.
async fn fill_top_track_durations(rp: &RustyPipe, artist: &mut MusicArtist) {
    if artist.tracks.iter().all(|t| t.duration.is_some()) {
        return;
    }
    let Some(playlist_id) = artist.tracks_playlist_id.clone() else {
        return;
    };
    let Ok(playlist) = rp.query().music_playlist(&playlist_id).await else {
        return;
    };

    let durations: HashMap<String, u32> = playlist
        .tracks
        .items
        .into_iter()
        .filter_map(|t| t.duration.map(|d| (t.id, d)))
        .collect();

    for track in &mut artist.tracks {
        if track.duration.is_none() {
            track.duration = durations.get(&track.id).copied();
        }
    }
}
