export const ROUTE_NAMES = {
  HOME: "home",
  ALBUM: "album",
  ARTIST: "artist",
  ARTIST_ALBUMS: "artist-albums",
  PLAYLIST: "playlist",
  LIKED: "liked",
  SETTINGS: "settings",
  SETTINGS_GENERAL: "settings-general",
  SETTINGS_AUDIO: "settings-audio",
  SETTINGS_STORAGE: "settings-storage",
  SETTINGS_PROXY: "settings-proxy",
  SETTINGS_SOURCES: "settings-sources",
  SETTINGS_LANGUAGE: "settings-language",
  SETTINGS_NOTIFICATIONS: "settings-notifications",
  SETTINGS_STATS: "settings-stats",
  SETTINGS_APPEARANCE: "settings-appearance",
  SETTINGS_ABOUT: "settings-about",
  SETTINGS_TERMS: "settings-terms",
  SETTINGS_PRIVACY: "settings-privacy",
  ALL_MUSIC: "all-music",
  YOUTUBE_PLAYLIST: "youtube-playlist",
  YOUTUBE_ALBUM: "youtube-album",
  YOUTUBE_ARTIST: "youtube-artist",
  DEV_RECO_STAND: "dev-reco-stand",
} as const;

export type AppRouteName = (typeof ROUTE_NAMES)[keyof typeof ROUTE_NAMES];
