import {
  IS_CHROMIUM,
  IS_MOBILE,
  IS_MOBILE_SAFARI,
  IS_SAFARI,
} from "./userAgent";

export const USE_NATIVE_SCROLL = IS_MOBILE;
export const IS_OVERLAY_SCROLL_SUPPORTED
  = IS_MOBILE || (!IS_CHROMIUM && (!IS_SAFARI || IS_MOBILE_SAFARI));

export const USE_CUSTOM_SCROLL
  = !USE_NATIVE_SCROLL && !IS_OVERLAY_SCROLL_SUPPORTED;
