/**
 * Format coverage for the import metadata stage.
 *
 * These tests run real (tiny) audio files through the same `parseMetadata`
 * entry point the metadata worker uses, so a regression in tag reading or
 * format detection for any supported container is caught here.
 *
 * Fixtures are generated by `fixtures/generate.sh` (ffmpeg, ~0.3s of a sine).
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseMetadata } from "@/workers/meta.worker";
import { normalizeMetadata } from "@/lib/metadata";
import { AUDIO_FILE_EXTENSIONS } from "../import/constants";
import { isValidImportItem } from "@/lib/environment/mimeSupport";

const FIXTURES = join(__dirname, "fixtures");

function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURES, name)));
}

async function parse(name: string, extractCover = true) {
  return parseMetadata({
    fileId: "test",
    fileName: name,
    fileData: fixture(name),
    extractCover,
  });
}

async function parseOk(name: string, extractCover = true) {
  const res = await parse(name, extractCover);
  if (!res.success) throw new Error(`Expected ${name} to parse, got: ${res.error}`);
  return res.meta;
}

/**
 * Every supported container, with the codec string music-metadata reports.
 * `tagged` is false for containers that carry no tag block (raw ADTS).
 */
const FORMATS = [
  { file: "sample.mp3", codec: "MPEG 1 Layer 3", lossless: false, sampleRate: 44100, tagged: true },
  { file: "sample.flac", codec: "FLAC", lossless: true, sampleRate: 44100, tagged: true },
  { file: "sample.wav", codec: "PCM", lossless: true, sampleRate: 44100, tagged: true },
  { file: "sample.ogg", codec: "Vorbis I", lossless: undefined, sampleRate: 44100, tagged: true },
  { file: "sample.opus", codec: "Opus", lossless: undefined, sampleRate: 48000, tagged: true },
  { file: "sample.m4a", codec: "MPEG-4/AAC", lossless: false, sampleRate: 44100, tagged: true },
  { file: "sample.aac", codec: "AAC", lossless: false, sampleRate: 44100, tagged: false },
  { file: "sample.webm", codec: "OPUS", lossless: undefined, sampleRate: 48000, tagged: true },
  { file: "sample.alac", codec: "ALAC", lossless: true, sampleRate: 44100, tagged: true },
  { file: "sample.wma", codec: "Windows Media Audio V8", lossless: undefined, sampleRate: undefined, tagged: true },
  // Not ffmpeg-generated (ffmpeg has no APE encoder): a vendored 1s impulse
  // from the ape-decoder test suite with an APEv2 tag appended. music-metadata
  // reports no codec string for APE, only the container.
  { file: "sample.ape", codec: undefined, lossless: true, sampleRate: 44100, tagged: true, durationRange: [0.9, 1.1] },
] as const;

describe("metadata parsing across audio formats", () => {
  describe.each(FORMATS)("$file", (format) => {
    const { file, codec, lossless, sampleRate, tagged } = format;
    // ffmpeg fixtures are a 0.3s sine; encoder padding shifts it slightly.
    const [minDuration, maxDuration] = "durationRange" in format ? format.durationRange : [0.25, 0.45];

    it("parses successfully", async () => {
      const res = await parse(file);
      expect(res.success).toBe(true);
    });

    it("reports the expected codec and stream properties", async () => {
      const meta = await parseOk(file);

      expect(meta.format.codec).toBe(codec);
      expect(meta.format.lossless).toBe(lossless);
      expect(meta.format.sampleRate).toBe(sampleRate);
      expect(meta.duration).toBeGreaterThan(minDuration);
      expect(meta.duration).toBeLessThan(maxDuration);
    });

    if (tagged) {
      it("extracts the embedded tags", async () => {
        const meta = await parseOk(file);

        expect(meta.title).toBe(file === "sample.wma" ? "sample" : "Fixture Title");
        expect(meta.artists).toEqual(["Fixture Artist"]);
        expect(meta.trackNo).toBe(3);
      });
    }
    else {
      it("falls back to the file name when the container carries no tags", async () => {
        const meta = await parseOk(file);

        expect(meta.title).toBe(file.replace(/\.[^.]+$/, ""));
        expect(meta.artists).toEqual([]);
      });
    }
  });

  it("covers every extension the file picker offers", () => {
    const covered = new Set(FORMATS.map(f => f.file.split(".").pop()));
    for (const ext of AUDIO_FILE_EXTENSIONS) {
      expect(covered, `no fixture for .${ext}`).toContain(ext);
    }
  });

  it("accepts every offered extension as a valid import item", () => {
    // The picker must never offer a format the pipeline will reject.
    for (const ext of AUDIO_FILE_EXTENSIONS) {
      expect(isValidImportItem(`song.${ext}`), `.${ext} rejected by validation`).toBe(true);
    }
  });
});

describe("tag edge cases", () => {
  it("falls back to the file name when the file has no tags", async () => {
    const meta = await parseOk("untagged.flac");

    expect(meta.title).toBe("untagged");
    expect(meta.artists).toEqual([]);
    expect(meta.album).toBe("");
  });

  it("keeps the numeric tags that are present", async () => {
    const meta = await parseOk("sample.flac");

    expect(meta.year).toBe(2024);
    expect(meta.trackNo).toBe(3);
    expect(meta.diskNo).toBe(1);
    expect(meta.album).toBe("Fixture Album");
  });

  it("normalizes an untagged parse into the Unknown Title placeholder", async () => {
    const raw = await parseOk("untagged.flac");
    const normalized = normalizeMetadata(
      { name: "untagged.flac", webkitRelativePath: "" } as File,
      { ...raw, title: "" },
    );

    expect(normalized.title).toBe("Unknown Title");
    expect(normalized.artists).toEqual([]);
  });

  it("derives the artist from the folder name for web imports without tags", async () => {
    const raw = await parseOk("untagged.flac");
    const normalized = normalizeMetadata(
      { name: "untagged.flac", webkitRelativePath: "Some Artist/untagged.flac" } as File,
      raw,
    );

    expect(normalized.artists).toEqual(["Some Artist"]);
  });
});

describe("cover art", () => {
  it("extracts an embedded cover as a typed blob", async () => {
    const meta = await parseOk("with-cover.mp3");

    expect(meta.pictureBlob).toBeInstanceOf(Blob);
    expect(meta.pictureBlob?.type).toBe("image/png");
    expect(meta.pictureBlob?.size).toBeGreaterThan(0);
  });

  it("skips the cover when extractCover is false", async () => {
    const meta = await parseOk("with-cover.mp3", false);

    expect(meta.pictureBlob).toBeUndefined();
    // Tags are still read.
    expect(meta.title).toBe("Fixture Title");
  });

  it("leaves pictureBlob undefined for files without cover art", async () => {
    const meta = await parseOk("sample.mp3");

    expect(meta.pictureBlob).toBeUndefined();
  });
});

describe("malformed input", () => {
  it.each([
    ["empty.mp3", "a zero-byte file"],
    ["corrupt.mp3", "random bytes with an audio extension"],
    ["not-audio.txt", "a plain text file"],
  ])("reports a parse failure for %s (%s)", async (file) => {
    const res = await parse(file);

    expect(res.success).toBe(false);
    if (!res.success) expect(res.error).toBeTruthy();
  });

  it("parses by content, not by extension", async () => {
    // A FLAC stream that arrived with an .mp3 name still parses as FLAC.
    const res = await parseMetadata({
      fileId: "test",
      fileName: "mislabeled.mp3",
      fileData: fixture("sample.flac"),
    });

    expect(res.success).toBe(true);
    if (res.success) expect(res.meta.format.codec).toBe("FLAC");
  });

  it("does not throw on a truncated stream", async () => {
    const full = fixture("sample.flac");
    const res = await parseMetadata({
      fileId: "test",
      fileName: "truncated.flac",
      fileData: full.slice(0, 200),
    });

    // Either outcome is acceptable; crashing the worker is not.
    expect(typeof res.success).toBe("boolean");
  });
});
